publisher:
  name: Ishan Lakhwani
  website: https://bluntbrain.vercel.app/
  email: ishan.lakhwani@gmail.com
app:
  name: NearMe
  address: 5aAgnw5wEDdRXPG1iFDpxDum63e3UmpwiqSBLymEJjqt
  android_package: com.bluntbrain.NearMe
  urls:
    license_url: https://github.com/Krane-Apps/solana-near-me/blob/master/LICENSE
    copyright_url: https://github.com/Krane-Apps/solana-near-me/blob/master/COPYRIGHT.md
    privacy_policy_url: https://github.com/Krane-Apps/solana-near-me/blob/master/docs/privacy-policy.md
    website: https://github.com/Krane-Apps/solana-near-me
  media:
    - purpose: icon
      uri: storeicon.png
release:
  address: Bmf2uuF7Gat3TsMqXpECspM3ZXoi92ZmSyKBDwSoKxZC
  media:
    - purpose: icon
      uri: storeicon.png
    - purpose: banner
      uri: banner.png
    - purpose: screenshot
      uri: ScreenShot_01.png
    - purpose: screenshot
      uri: ScreenShot_02.png
    - purpose: screenshot
      uri: ScreenShot_03.png
    - purpose: screenshot
      uri: ScreenShot_04.png
    - purpose: screenshot
      uri: ScreenShot_05.png
  files:
    - purpose: install
      uri: NearMe-v1.0.6-production.apk
  catalog:
    en-US:
      name: NearMe - Solana Mobile Payment dApp
      short_description: Google Maps for Solana
      long_description: |
        Solana Near Me is like Google Maps, but for Solana. It helps users discover nearby Solana merchants and pay them directly via a mobile app. Today, merchants want to accept crypto but can't reach users, and users don't know where to spend it—this app solves that disconnect.

        🗺️ Key Features:
        • Map-like UI to find and navigate to local Solana merchants
        • 7,000+ merchants live at launch
        • Referral rewards to drive growth
        • Native Solana Pay support—no browser wallet needed
        • Verified proof-of-location merchants
        • Built-in swaps and onramps via Jupiter, MoonPay
        • One-tap merchant signup using Google Maps URL
        • Merchant NFT badges for reputation
        • Fast, cheap payments using Solana's speed and low fees
        • Fully Solana-native, built for mobile

        🚀 Launch, explore, and pay with Solana: effortlessly.

        Built with React Native and Mobile Wallet Adapter for seamless crypto payments at local merchants. Uses Firebase Realtime Database for instant merchant discovery and supports both SOL and USDC transactions with real-time exchange rates.
      new_in_version: |
        Version 1.0.6 - Enhanced 3D mapping experience and improved performance.

        ✨ What's new in this update:
        • Revolutionary 3D map interface with Mapbox GL
        • Enhanced marker clustering for better performance with 7000+ merchants
        • Improved zoom controls and 3D earth visualization
        • Better user location tracking and navigation
        • Optimized performance for large datasets
        • Enhanced dark mode with Solana branding colors
      saga_features: |
        Built for Solana Mobile with native wallet integration:

        📱 Mobile Wallet Adapter:
        • Connect any Solana wallet (Phantom, Solflare, etc.)
        • Sign transactions securely without sharing private keys
        • One-tap wallet connection

        💳 Solana Pay:
        • Pay merchants with SOL or USDC
        • Generate QR codes for payments
        • Fast, cheap transactions

        🗺️ Mobile-First Design:
        • Native Android app with smooth performance
        • GPS location for finding nearby merchants
        • Works offline after first load
solana_mobile_dapp_publisher_portal:
  testing_instructions: |
    NearMe - Solana Mobile Payment dApp Testing Instructions

    📱 Prerequisites:
    • Android device with Android 6.0+ (API level 23+)
    • Install a MWA-compatible wallet (Phantom, Solflare, or Backpack recommended)
    • Enable location services for map functionality
    • Stable internet connection for blockchain interactions

    🧪 Testing Steps:

    1. App Launch & Onboarding:
       • Launch NearMe app
       • Review welcome screen and feature highlights
       • Tap "Get Started" to proceed to main map screen

    2. Map & Location Features:
       • Verify map loads with merchant markers in Bangalore area
       • Test location permission request and approval
       • Verify purple Solana-branded map pins are displayed
       • Test category filtering functionality
       • Tap on merchant markers to view details

    3. Wallet Connection:
       • Navigate to Profile or Payment section
       • Tap "Connect Wallet" button
       • Verify Mobile Wallet Adapter launches properly
       • Connect using installed wallet (Phantom/Solflare/etc.)
       • Confirm wallet address is displayed correctly

    4. Payment Flow Testing:
       • Select a merchant from the map
       • Choose "Pay with Crypto" option
       • Enter a test amount (recommend $1-5 USD equivalent)
       • Select SOL or USDC token for payment
       • Verify real-time exchange rate calculation
       • Review transaction summary
       • Complete payment through wallet signing
       • Verify transaction success screen
       • Check 1% SOL cashback calculation

    5. Rewards & Profile:
       • Navigate to Rewards screen
       • Verify SOL balance display
       • Check transaction history
       • Test achievement progress tracking
       • Verify NFT badge collection interface

    🔍 Key Areas to Test:
    • Mobile Wallet Adapter integration and signing
    • Real-time SOL/USDC price fetching
    • Firebase merchant data loading (should be instant after first load)
    • Location-based merchant filtering
    • Transaction completion and confirmation
    • Reward calculation accuracy
    • Dark theme UI consistency

    ⚠️ Important Notes:
    • App uses DEVNET for testing - no real funds required
    • Merchant data is sourced from CryptWerk database (Bangalore area)
    • Firebase Realtime Database provides optimized performance
    • All transactions are real Solana blockchain interactions
    • Location services required for optimal experience

    📊 Expected Performance:
    • Initial app load: ~2-3 seconds
    • Merchant data loading: 1.5 seconds first time, instant thereafter
    • Map rendering: <1 second
    • Wallet connection: 2-5 seconds
    • Transaction signing: Depends on wallet app

    🐛 Known Limitations:
    • Currently focused on Bangalore merchants only
    • Requires Android (iOS not supported in current version)
    • Some merchants may not have complete address information
    • Devnet transactions only for testing

    For issues or questions, contact: ishan.lakhwani@gmail.com
lastSubmittedVersionOnChain:
  address: Bmf2uuF7Gat3TsMqXpECspM3ZXoi92ZmSyKBDwSoKxZC
  version_code: 4
  apk_hash: HOneNGguunANX7421mHAvynWGh8R93Ld2H8OmZP6W9k=
lastUpdatedVersionOnStore:
  address: Bmf2uuF7Gat3TsMqXpECspM3ZXoi92ZmSyKBDwSoKxZC
